apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-demo
  namespace: argocd  # Application 必须放在 ArgoCD 命名空间
spec:
  project: default
  syncPolicy:
    automated:  # 自动同步 Git 变更
      prune: true  # 删除 Git 中不存在的资源
      selfHeal: true  # 集群状态漂移时自动修复
  source:
    repoURL: git@github.com/2661210016/argocd-demo.git
    targetRevision: main
    path: k8s/nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: default  #应用部署在那个空间
